version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: pets-db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: petsdb
      TZ: America/Sao_Paulo
    ports:
      - "5436:5432"   # mapeia porta 5436 no host para 5432 no container
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pets-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8083:80"   # pgAdmin acess√≠vel em http://localhost:8083
    depends_on:
      - postgres

volumes:
  postgres_data:
